APP/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

app_name = "APP"

urlpatterns = [
    path("", views.index, name="index"),
    path("homepage.html", views.index, name="index"),
    path("index.html", views.login, name="login"),
    path("login.html", views.login, name="login"),
    path("convert.html", views.convert, name="convert"),
    path("dashboard.html", views.dashboard, name="dashboard"),
    path("explore.html", views.explore, name="explore"),
    path("mybooks.html", views.mybooks, name="mybooks"),
    path("register.html", views.register, name="register"),
    path("genre.html", views.genre, name="genre"),
    path("genre-all.html", views.genre_all, name="genre_all"),
    path("logout.html", views.logout, name="logout"),
    path("contribute.html", views.contribute, name="contribute"),
    path("featured.html", views.featured, name="featured"),
    path("settings.html", views.settings, name="settings")



]

AUDIOCATE/urls.py
from django.contrib import admin
from . import  settings
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("APP.urls")),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

APP/templates/examples/Home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="{% static './Home.css' %}" rel="stylesheet"/>
  <link crossorigin="anonymous" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css' %}" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" rel="stylesheet"/>
  <script src="Home.js">
  </script>
  <title>
   AudioCate
  </title>
 </head>
 <body>
  <main class="wrapper">
   <div class="container">
    <div class="nav-open">
     <span class="header">
      <ion-icon class="menu-open" name="menu-outline">
      </ion-icon>
      <img alt="logo" height="75px" src="{% static '../Landing Page/images/AudioCate-removebg-preview.png' %}"/>
      <h1>
       AudioCate
      </h1>
     </span>
    </div>
    <div class="side-bar">
     <ion-icon class="menu-close" name="close-outline">
     </ion-icon>
     <a class="header" href="../Landing Page/homepage.html">
      <img alt="logo" height="75px" src="{% static '../Landing Page/images/AudioCate-removebg-preview.png' %}"/>
      <h1>
       AudioCate
      </h1>
     </a>
     <ul>
      <li>
       <a href="Home.html">
        <ion-icon name="sync">
        </ion-icon>
        <span>
         Convert
        </span>
       </a>
      </li>
      <li>
       <a href="#">
        <ion-icon name="book">
        </ion-icon>
        <span>
         My Books
        </span>
       </a>
      </li>
      <li>
       <a href="#">
        <ion-icon name="search-circle">
        </ion-icon>
        <span>
         Explore
        </span>
       </a>
      </li>
      <li>
       <a href="#">
        <i class="fas fa-people-carry">
        </i>
        <span>
         Contribute
        </span>
       </a>
      </li>
      <li>
       <a href="#">
        <ion-icon name="grid">
        </ion-icon>
        <span>
         Genres
        </span>
       </a>
      </li>
      <li>
       <a href="#">
        <ion-icon name="settings">
        </ion-icon>
        <span>
         Settings
        </span>
       </a>
      </li>
      <li>
       <a class="logout" href="#">
        <ion-icon name="log-out-outline">
        </ion-icon>
        <span>
         Log out
        </span>
       </a>
      </li>
     </ul>
     <div class="overlay">
     </div>
    </div>
    <div class="display">
     <div class="upload">
      <div class="text-display">
       <textarea cols="30" id="text-input" name="input" rows="10">Type, paste or edit text here</textarea>
      </div>
      <div id="img-display">
       <p>
        Select Image file
       </p>
       <input accept="image/*" multiple="" onchange="handleFiles(this.files)" type="file"/>
      </div>
     </div>
     <div class="voice-select">
      <label for="voice">
      </label>
      <select id="voice" name="voice">
       <option disabled="" selected="" value="Male">
        Select preferred voice
       </option>
       <option value="Male">
        Male
       </option>
       <option value="Female">
        Female
       </option>
      </select>
      <div id="conversion">
      </div>
     </div>
     <div>
     </div>
     <div class="actions">
      <div class="save">
       <button>
        Save
       </button>
      </div>
      <div class="play">
       <button>
        Play
       </button>
      </div>
      <div class="delete">
       <button>
        Delete
       </button>
      </div>
     </div>
    </div>
   </div>
  </main>
  <script src="{% static 'https://unpkg.com/ionicons@5.2.3/dist/ionicons.js' %}">
  </script>
 </body>
</html>

APP/templates/examples/contribute.html
{% load static %}

<!--
=========================================================
* Argon Dashboard - v1.2.0
=========================================================
* Product Page: https://www.creative-tim.com/product/argon-dashboard


* Copyright  Creative Tim (http://www.creative-tim.com)
* Coded by www.creative-tim.com



=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
  <meta content="Start your development with a Dashboard for Bootstrap 4." name="description"/>
  <meta content="Creative Tim" name="author"/>
  <title>
   Argon Dashboard - Free Dashboard for Bootstrap 4
  </title>
  <!-- Favicon -->
  <link href="{% static 'assets/img/brand/favicon.png' %}" rel="icon" type="image/png"/>
  <!-- Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' %}" rel="stylesheet"/>
  <!-- Icons -->
  <link href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet" type="text/css"/>
  <link href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"/>
  <!-- Argon CSS -->
  <link href="{% static 'assets/css/argon.css' %}" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <!-- Sidenav -->
  <nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
   <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header align-items-center">
     <a class="navbar-brand" href="javascript:void(0)">
      <img alt="..." class="navbar-brand-img" src="{% static '/assets/img/images/AudioCate-removebg-preview.png' %}"/>
      <h1>
       AudioCate
      </h1>
     </a>
    </div>
    <div class="navbar-inner">
     <!-- Collapse -->
     <div class="collapse navbar-collapse" id="sidenav-collapse-main">
      <!-- Nav items -->
      <ul class="navbar-nav">
       <li class="nav-item">
        <a class="nav-link" href="dashboard.html">
         <i class="ni ni-tv-2 text-primary">
         </i>
         <span class="nav-link-text">
          Dashboard
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="mybooks.html">
         <i class="ni ni-planet text-orange">
         </i>
         <span class="nav-link-text">
          My Books
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="explore.html">
         <i class="ni ni-pin-3 text-primary">
         </i>
         <span class="nav-link-text">
          Explore
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="featured.html">
         <i class="ni ni-pin-3 text-primary">
         </i>
         <span class="nav-link-text">
          Featured
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link active" href="contribute.html">
         <i class="ni ni-single-02 text-yellow">
         </i>
         <span class="nav-link-text">
          Contribute
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="genre.html">
         <i class="ni ni-bullet-list-67 text-default">
         </i>
         <span class="nav-link-text">
          Genres
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="login.html">
         <i class="ni ni-key-25 text-info">
         </i>
         <span class="nav-link-text">
          Login
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="convert.html">
         <i class="ni ni-circle-08 text-pink">
         </i>
         <span class="nav-link-text">
          Convert
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="settings.html">
         <i class="ni ni-send text-dark">
         </i>
         <span class="nav-link-text">
          Profile
         </span>
        </a>
       </li>
      </ul>
     </div>
    </div>
   </div>
  </nav>
  <!-- Main content -->
  <div class="main-content" id="panel">
   <!-- Topnav -->
   <!-- Header -->
   <!-- Header -->
   <div class="header pb-6 d-flex align-items-center" style="min-height: 500px; background-image: url(assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8">
      <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
       <li class="breadcrumb-item">
        <a href="#">
         <i class="fas fa-home">
         </i>
        </a>
       </li>
       <li class="breadcrumb-item">
        <a href="dashboard.html">
         Home
        </a>
       </li>
      </ol>
    </span>
    <!-- Header container -->
    <div class="container-fluid d-flex align-items-center">
     <div class="row">
      <div class="col-lg-7 col-md-10">
       <h1 class="display-2 text-white">
        Contribute to our Official Books
       </h1>
      </div>
     </div>
    </div>
   </div>
   <!-- Page content -->
   <div class="container-fluid mt--6">
      <center>
     <div class="col-xl-8 order-xl-1">
      <div class="card">
        <center>
       <div class="card-header">
        <div class="row align-items-center">
         <div class="col-8">
          <h3 class="mb-0">
           Contirubute To Our Library of Audio Books
          </h3>
         </div>
        </div>
       </div>
       </center>
       <div class="card-body">
        <form method="POST" action="{% url 'APP:contribute' %}" enctype="multipart/form-data" >
          {% csrf_token %}
         <h6 class="heading-small text-muted mb-4">
          User and Audio Book Info
         </h6>
         <div class="pl-lg-4">
          <div class="row">
             <input name="username" type="hidden" value="{{user.username}}"/>
           <div class="col-lg-6">
            <div class="form-group">
             <label class="form-control-label" for="input-email">
            Author's Name
             </label>
             <input class="form-control" id="input-email" placeholder="john doe" name="name" type="text" />
            </div>
           </div>
          <div class="col-lg-6">
           <div class="form-group">
            <label class="form-control-label" for="input-last-name">
             Author's Picture
            </label>
            <input class="form-control" id="input-last-name" type="file" name="authors_image"/>
           </div>
          </div>
          <div class="col-lg-6">
           <div class="form-group">
            <label class="form-control-label" for="input-last-name">
             Author's Email
            </label>
            <input class="form-control" id="input-last-name" type="email" placeholder="johndoe@example.com" name="email"/>
           </div>
          </div>
          <div class="col-lg-6">
           <div class="form-group">
            <label class="form-control-label" for="input-last-name">
             Book Cover Image
            </label>
            <input class="form-control" id="input-last-name" type="file" name="cover_image" />
           </div>
          </div>
          <div class="col-lg-6">
           <div class="form-group">
            <label class="form-control-label" for="input-first-name">
             Book Title
            </label>
            <input class="form-control" id="input-first-name" placeholder="book title" name="title" type="text" required/>
           </div>
          </div>
           <div class="col-lg-6">
            <div class="form-group">
             <label class="form-control-label" for="input-first-name">
              Summary
             </label>
             <input class="form-control" id="input-first-name" placeholder="book summary" name="summary" type="text" required/>
            </div>
           </div>
           <div class="col-lg-6">
            <div class="form-group">
             <label class="form-control-label" for="input-last-name">
              Audio File
             </label>
             <input class="form-control" id="input-last-name" type="file" name="audio" required/>
            </div>
           </div>
           <div class="col-lg-6">
            <div class="form-group">
             <label class="form-control-label" for="input-last-name">
              Link to Audio File
             </label>
             <input class="form-control" id="input-last-name" type="text" name="link" required/>
            </div>
           </div>
          </div>
         </div>
         <hr class="my-4">
          <!-- Address -->
          <hr class="my-4"/>
          <!-- Description -->
          {{message}}
         </hr>
         <button class="btn btn-primary btn-lg" type="submit">
          Update
        </button>
        </form>
       </div>
      </div>
     </div>
     </center>
    <!-- Footer -->
    <footer class="footer pt-0">
     <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
       <div class="copyright text-center text-lg-left text-muted">
        © 2020
        <a class="font-weight-bold ml-1" href="https://www.creative-tim.com" target="_blank">
         TEAM GREEN
        </a>
       </div>
      </div>
      <div class="col-lg-6">
       <ul class="nav nav-footer justify-content-center justify-content-lg-end">
        <li class="nav-item">
         <a class="nav-link" href="" target="_blank">
          Creative Tim
         </a>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="" target="_blank">
          MIT License
         </a>
        </li>
       </ul>
      </div>
     </div>
    </footer>
   </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}">
  </script>
  <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}">
  </script>
  <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}">
  </script>
  <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}">
  </script>
  <script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}">
  </script>
  <!-- Argon JS -->
  <script src="{% static 'assets/js/argon.js?v=1.2.0' %}">
  </script>
 </body>
</html>

APP/templates/examples/convert.html
{% load static %}
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
  <meta content="Start your development with a Dashboard for Bootstrap 4." name="description"/>
  <meta content="Creative Tim" name="author"/>
  <title>
   AUDIOCATE- CONVERT YOUR BOOK TO AUDIO
  </title>
  <!-- Favicon -->
  <link href="{% static './assets/img/brand/favicon.png' %}" rel="icon" type="image/png"/>
  <!-- Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' %}" rel="stylesheet"/>
  <!-- Icons -->
  <link href="{% static './assets/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet" type="text/css"/>
  <link href="{% static './assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"/>
  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link href="{% static './assets/css/argon.css' %}" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <!-- Sidenav -->
  <nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
   <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header align-items-center">
     <a class="navbar-brand" href="javascript:void(0)">
      <img alt="..." class="navbar-brand-img" src="{% static '/assets/img/images/AudioCate-removebg-preview.png' %}"/>
      <h1>
       AudioCate
      </h1>
     </a>
    </div>
    <div class="navbar-inner">
     <!-- Collapse -->
     <div class="collapse navbar-collapse" id="sidenav-collapse-main">
      <!-- Nav items -->
      <ul class="navbar-nav">
       <li class="nav-item">
        <a class="nav-link" href="dashboard.html">
         <i class="ni ni-tv-2 text-primary">
         </i>
         <span class="nav-link-text">
          Dashboard
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="mybooks.html">
         <i class="ni ni-planet text-orange">
         </i>
         <span class="nav-link-text">
          My Books
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="explore.html">
         <i class="ni ni-pin-3 text-primary">
         </i>
         <span class="nav-link-text">
          Explore
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="featured.html">
         <i class="ni ni-pin-3 text-primary">
         </i>
         <span class="nav-link-text">
          Featured
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="contribute.html">
         <i class="ni ni-single-02 text-yellow">
         </i>
         <span class="nav-link-text">
          Contribute
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="genre.html">
         <i class="ni ni-bullet-list-67 text-default">
         </i>
         <span class="nav-link-text">
          Genres
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="login.html">
         <i class="ni ni-key-25 text-info">
         </i>
         <span class="nav-link-text">
          Login
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link active" href="convert.html">
         <i class="ni ni-circle-08 text-pink">
         </i>
         <span class="nav-link-text">
          Convert
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="settings.html">
         <i class="ni ni-send text-dark">
         </i>
         <span class="nav-link-text">
          Profile
         </span>
        </a>
       </li>
      </ul>
     </div>
    </div>
   </div>
  </nav>
  <!-- Main content -->
  <div class="main-content" id="panel">
   <!-- Topnav -->
   <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center ml-md-auto">
       <li class="nav-item d-xl-none">
        <!-- Sidenav toggler -->
        <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
         <div class="sidenav-toggler-inner">
          <i class="sidenav-toggler-line">
          </i>
          <i class="sidenav-toggler-line">
          </i>
          <i class="sidenav-toggler-line">
          </i>
         </div>
        </div>
       </li>
      </ul>
      <ul class="navbar-nav align-items-center ml-auto ml-md-0">
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link pr-0" data-toggle="dropdown" href="#" role="button">
         <div class="media align-items-center">
          <span class="avatar avatar-sm rounded-circle">
           <img alt="Image placeholder" src="{% if user.profile.image %}{{user.profile.image.url}}{% else %}{% static 'assets/img/theme/team-4.jpg' %}{% endif %}"/>
          </span>
          <div class="media-body ml-2 d-none d-lg-block">
           <span class="mb-0 text-sm font-weight-bold">
          {{user.username}}
           </span>
          </div>
         </div>
        </a>
       </li>
      </ul>
     </div>
    </div>
   </nav>
   <!-- Header -->
   <!-- Header -->
   <div class="header bg-primary pb-6">
    <div class="container-fluid">
     <div class="header-body">
      <div class="row align-items-center py-4">
       <div class="col-lg-6 col-7">
        <h6 class="h2 text-white d-inline-block mb-0">
         Convert
        </h6>
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
         <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
          <li class="breadcrumb-item">
           <a href="#">
            <i class="fas fa-home">
            </i>
           </a>
          </li>
          <li class="breadcrumb-item">
           <a href="#">
            Upload
           </a>
          </li>
          <li aria-current="page" class="breadcrumb-item active">
           Convert
          </li>
         </ol>
        </nav>
       </div>
      </div>
     </div>
    </div>
   </div>
   <!-- Page content -->
   <div class="container-fluid mt--6">
    <div class="row justify-content-center">
     <div class="col">
      <div class="card">
       <div class="card-header bg-transparent">
         {% if message %}
         <h3 class="mb-0" style="color:red;">
             {{message}}
         </h3>
         {% endif %}
        <h3 class="mb-0">
         Convert Your Images or PDF's To Audio Books
        </h3>
       </div>
       <div class="card-body">
        <form method="POST" action="{% url 'APP:convert' %}" enctype="multipart/form-data">
          {% csrf_token %}
         <div class="row icon-examples">
          Upload Per Page for Pdf or Images
            {% if finish %}
            {% else %}
          <div class="mt-2 col-lg-3 col-md-6">
           <input name="file" type="file"/>
          </div>
          <div class="mt-2 col-lg-3 col-md-6">
           <div class="custom-control custom-radio custom-control-inline">
            <input class="custom-control-input" id="customRadioInline1" name="voice" value="en-UK" type="radio"/>
            <label class="custom-control-label" for="customRadioInline1">
             Engish UK Voice for the AudioBook
            </label>
           </div>
           <div class="custom-control custom-radio custom-control-inline">
            <input class="custom-control-input" id="customRadioInline2" name="voice" value="en-US" type="radio"/>
            <label class="custom-control-label" for="customRadioInline2">
             English US Voice for the AudioBook
            </label>
           </div>
          </div>
          <div class="p-4 bg-secondary">
           Name of AudioBook
           <input class="form-control" id="example-text-input" name="name" placeholder="Name of AudioBook" type="text"/>
          </div>
          {% endif %}
          {% if finish %}
          <center>
          <div class="mt-2 col-lg-3 col-md-6">
           <a class="btn btn-primary btn-lg" href="{{link}}" download="{{name}}">
            Download
          </a>
          </div>
          <div class="mt-2 col-lg-3 col-md-6">
           <button class="btn btn-danger btn-lg">
            Clear
           </button>
          </div>
          <input type="hidden" name="publish" value="true"/>
          <input type="hidden" name="name" value="{{item.name}}" />
          <input type="hidden" name="link" value="{{item.link}}" />
          <input type="hidden" name="voice" value="{{item.voice}}" />
          <div class="mt-2 col-lg-3 col-md-6">
           <button class="btn btn-danger btn-lg" type="submit">
            Publish
           </button>
          </div>
          </center>
          {% else %}
          <div class="mt-2 col-lg-3 col-md-6">
           <button class="btn btn-primary btn-lg" type="submit">
            Submit
           </button>
          </div>
          {% endif %}
         </div>
        </form>
       </div>
      </div>
     </div>
    </div>
   </div>
   <!-- Footer -->
   <footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
     <div class="col-lg-6">
      <div class="copyright text-center text-lg-left text-muted">
       © 2020
       <a class="font-weight-bold ml-1" href="https://www.creative-tim.com" target="_blank">
        TEAM GREEN
       </a>
      </div>
     </div>
     <div class="col-lg-6">
      <ul class="nav nav-footer justify-content-center justify-content-lg-end">
       <li class="nav-item">
        <a class="nav-link" href="" target="_blank">
         Creative Tim
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="" target="_blank">
         MIT License
        </a>
       </li>
      </ul>
     </div>
    </div>
   </footer>
  </div>
 </body>
</html>
<!-- Argon Scripts -->
<!-- Core -->
<script src="{% static './assets/vendor/jquery/dist/jquery.min.js' %}">
</script>
<script src="{% static './assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}">
</script>
<script src="{% static './assets/vendor/js-cookie/js.cookie.js' %}">
</script>
<script src="{% static './assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}">
</script>
<script src="{% static './assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}">
</script>
<!-- Optional JS -->
<script src="{% static './assets/vendor/clipboard/dist/clipboard.min.js' %}">
</script>
<!-- Argon JS -->
<script src="{% static './assets/js/argon.js' %}">
</script>