APP/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

app_name = "APP"

urlpatterns = [
    path("", views.index, name="index"),
    path("homepage.html", views.index, name="index"),
    path("index.html", views.login, name="login"),
    path("login.html", views.login, name="login"),
    path("convert.html", views.convert, name="convert"),
    path("dashboard.html", views.dashboard, name="dashboard"),
    path("explore.html", views.explore, name="explore"),
    path("mybooks.html", views.mybooks, name="mybooks"),
    path("register.html", views.register, name="register"),
    path("genre.html", views.genre, name="genre"),
    path("genre-all.html", views.genre_all, name="genre_all"),
    path("logout.html", views.logout, name="logout"),
    path("contribute.html", views.contribute, name="contribute"),
    path("featured.html", views.featured, name="featured"),
    path("settings.html", views.settings, name="settings")



]

AUDIOCATE/urls.py
from django.contrib import admin
from . import  settings
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("APP.urls")),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

APP/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="{% static 'homepage.css' %}" rel="stylesheet"/>
  <title>
   Home Page
  </title>
 </head>
 <body>
  <main class="container">
   <div class="right">
    <section class="header">
     <a class="header-link" href="homepage.html">
      <img alt="logo" src="{% static 'images/AudioCate-removebg-preview.png' %}" width="100px"/>
      <span>
       AudioCate
      </span>
     </a>
    </section>
    <div class="img-area">
     <img alt="image" id="img" src="{% static 'images/onbook.jpg' %}"/>
    </div>
   </div>
   <div class="text-area">
    <article>
     <h2>
      LET YOUR BOOK DO THE TALKING
     </h2>
     <p>
      <b>
       AudioCate
      </b>
      is the future of education. Convert your books in image and text format into personalised audio books. Listen to get a better feel and understanding.
     </p>
    </article>
    <form action="index.html">
     <button type="submit">
      Get Started
     </button>
    </form>
   </div>
  </main>
  <footer class="footer" id="footer">
  </footer>
  <script src="{% static 'saucecode.js' %}">
  </script>
 </body>
</html>

APP/templates/index.html
{% load static %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet"/>
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
  <link href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
  <link href="https://fonts.googleapis.com/css2?family=Rubik&amp;display=swap" rel="stylesheet"/>
  <link href="{% static 'main.css' %}" rel="stylesheet"/>
  <title>
   Login
  </title>
 </head>
 <body>
  <div class="home-wrapper">
   <div class="container-fluid">
    <nav class="navbar navbar-expand-sm bg-custom bg-transparent sticky-top">
     <a class="navbar-brand" href="homepage.html">
      <img alt="AudioCate Logo" src="{% static './images/AudioCate-removebg-preview.png' %}" width="75px"/>
      AudioCate
     </a>
     <div class="collapse navbar-collapse" id="nav_collapse">
      <ul class="navbar-nav ml-auto bg-custom">
       <li class="navbar-item">
        <a class="nav-link" href="homepage.html">
         Home
        </a>
       </li>
       <li class="navbar-item">
        <a class="nav-link" href="#">
         Contact Us
        </a>
       </li>
      </ul>
     </div>
    </nav>
    <div class="login-container">
     <img alt="reader" class="hero" src="{% static './images/male-reader.jpg' %}" width="100px"/>
     <form class="user-login" method="POST">
      {% csrf_token %}
      <h1 class="header-text">
       User Login
      </h1>
      <div class="email-input">
       <i class="fa">
       </i>
       <input class="container-fluid" name="email" placeholder="Email" type="email"/>
      </div>
      <div class="password-input">
       <input class="container-fluid" min="6" name="password" placeholder="Password" type="password"/>
      </div>
      <div class="login">
       <input class="container-fluid" type="submit" value="LOGIN"/>
      </div>
      {{message}}
      <div class="recovery">
       <a href="#">
        Forgot Password
       </a>
      </div>
      <div class="sign-up">
       <p class="sign-up">
        Don't have an account?
        <a href="register.html">
         Sign Up
        </a>
       </p>
      </div>
     </form>
    </div>
   </div>
  </div>
  <footer class="footer" id="footer">
  </footer>
  <script crossorigin="anonymous" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" src="https://code.jquery.com/jquery-3.4.1.slim.min.js">
  </script>
  <script crossorigin="anonymous" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js">
  </script>
  <script crossorigin="anonymous" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js">
  </script>
  <script src="{% static 'saucecode.js' %}">
  </script>
 </body>
</html>

APP/templates/register.html
{% load static %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link crossorigin="anonymous" href="{% static 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %}" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet"/>
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
  <link href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
  <link href="https://fonts.googleapis.com/css2?family=Rubik&amp;display=swap" rel="stylesheet"/>
  <link href="{% static 'main.css' %}" rel="stylesheet"/>
  <title>
   Login
  </title>
 </head>
 <body>
  <div class="home-wrapper">
   <div class="container-fluid">
    <nav class="navbar navbar-expand-sm bg-custom bg-transparent sticky-top">
     <a class="navbar-brand" href="homepage.html">
      <img alt="AudioCate Logo" src="{% static './images/AudioCate-removebg-preview.png' %}" width="75px"/>
      AudioCate
     </a>
     <button class="navbar-toggler navbar-dark" data-target="#nav_collapse" data-toggle="collapse" type="button">
      <span class="navbar-toggler-icon">
      </span>
     </button>
     <div class="collapse navbar-collapse" id="nav_collapse">
      <ul class="navbar-nav ml-auto bg-custom">
       <li class="navbar-item">
        <a class="nav-link" href="homepage.html">
         Home
        </a>
       </li>
       <li class="navbar-item">
        <a class="nav-link" href="#">
         Contact Us
        </a>
       </li>
      </ul>
     </div>
    </nav>
    <div class="login-container">
     <img alt="reader" class="hero" src="{% static './images/male-reader.jpg' %}" width="100px"/>
     <form class="user-login" method="POST">
      {% csrf_token %}
      <strong style="color:red">{{message}}</strong>
      <h1 class="header-text">
       User Register
      </h1>
      <div class="email-input">
       <i class="fa">
       </i>
       <input class="container-fluid" name="name" placeholder="Full name" type="text"/>
      </div>
      <div class="email-input">
       <i class="fa">
       </i>
       <input class="container-fluid" name="email" placeholder="Email" type="email"/>
      </div>
      <div class="password-input">
       <input class="container-fluid" min="6" name="password1" placeholder="Password" type="password"/>
      </div>
      <div class="password-input">
       <input class="container-fluid" min="6" name="password2" placeholder="Confirm Password" type="password"/>
      </div>
      <div class="login">
       <input class="container-fluid" type="submit" value="Register"/>
      </div>
      <div class="recovery">
       <a href="#">
        Forgot Password
       </a>
      </div>
      <div class="sign-up">
       <p class="sign-up">
        <a href="index.html">
         Login
        </a>
       </p>
      </div>
     </form>
    </div>
   </div>
  </div>
  <footer class="footer" id="footer">
  </footer>
  <script crossorigin="anonymous" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" src="{% static 'https://code.jquery.com/jquery-3.4.1.slim.min.js' %}">
  </script>
  <script crossorigin="anonymous" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" src="{% static 'https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js' %}">
  </script>
  <script crossorigin="anonymous" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" src="{% static 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js' %}">
  </script>
  <script src="{% static 'saucecode.js' %}">
  </script>
 </body>
</html>

APP/templates/settings.html
{% load static %}

<!--
=========================================================
* Argon Dashboard - v1.2.0
=========================================================
* Product Page: https://www.creative-tim.com/product/argon-dashboard


* Copyright  Creative Tim (http://www.creative-tim.com)
* Coded by www.creative-tim.com



=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
  <meta content="Start your development with a Dashboard for Bootstrap 4." name="description"/>
  <meta content="Creative Tim" name="author"/>
  <title>
   Argon Dashboard - Free Dashboard for Bootstrap 4
  </title>
  <!-- Favicon -->
  <link href="{% static 'assets/img/brand/favicon.png' %}" rel="icon" type="image/png"/>
  <!-- Fonts -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' %}" rel="stylesheet"/>
  <!-- Icons -->
  <link href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet" type="text/css"/>
  <link href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"/>
  <!-- Argon CSS -->
  <link href="{% static 'assets/css/argon.css' %}" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <!-- Sidenav -->
  <nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
   <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header align-items-center">
     <a class="navbar-brand" href="javascript:void(0)">
      <img alt="..." class="navbar-brand-img" src="{% static '/assets/img/images/AudioCate-removebg-preview.png' %}"/>
      <h1>
       AudioCate
      </h1>
     </a>
    </div>
    <div class="navbar-inner">
     <!-- Collapse -->
     <div class="collapse navbar-collapse" id="sidenav-collapse-main">
      <!-- Nav items -->
      <ul class="navbar-nav">
       <li class="nav-item">
        <a class="nav-link" href="dashboard.html">
         <i class="ni ni-tv-2 text-primary">
         </i>
         <span class="nav-link-text">
          Dashboard
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="mybooks.html">
         <i class="ni ni-planet text-orange">
         </i>
         <span class="nav-link-text">
          My Books
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="explore.html">
         <i class="ni ni-pin-3 text-primary">
         </i>
         <span class="nav-link-text">
          Explore
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="featured.html">
         <i class="ni ni-pin-3 text-primary">
         </i>
         <span class="nav-link-text">
          Featured
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="contribute.html">
         <i class="ni ni-single-02 text-yellow">
         </i>
         <span class="nav-link-text">
          Contribute
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="genre.html">
         <i class="ni ni-bullet-list-67 text-default">
         </i>
         <span class="nav-link-text">
          Genres
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="login.html">
         <i class="ni ni-key-25 text-info">
         </i>
         <span class="nav-link-text">
          Login
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="convert.html">
         <i class="ni ni-circle-08 text-pink">
         </i>
         <span class="nav-link-text">
          Convert
         </span>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link active" href="settings.html">
         <i class="ni ni-send text-dark">
         </i>
         <span class="nav-link-text">
          Profile
         </span>
        </a>
       </li>
      </ul>
     </div>
    </div>
   </div>
  </nav>
  <!-- Main content -->
  <div class="main-content" id="panel">
   <!-- Topnav -->
   <!-- Header -->
   <!-- Header -->
   <div class="header pb-6 d-flex align-items-center" style="min-height: 500px; background-image: url(assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8">
      <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
       <li class="breadcrumb-item">
        <a href="#">
         <i class="fas fa-home">
         </i>
        </a>
       </li>
       <li class="breadcrumb-item">
        <a href="dashboard.html">
         Home
        </a>
       </li>
      </ol>
    </span>
    <!-- Header container -->
    <div class="container-fluid d-flex align-items-center">
     <div class="row">
      <div class="col-lg-7 col-md-10">
       <h1 class="display-2 text-white">
        Hello {{user.username}}
       </h1>
       <p class="text-white mt-0 mb-5">
        This is your profile page. You can see your profile details and edit them here.
       </p>
      </div>
     </div>
    </div>
   </div>
   <!-- Page content -->
   <div class="container-fluid mt--6">
    <div class="row">
     <div class="col-xl-4 order-xl-2">
      <div class="card card-profile">
       <img alt="Image placeholder" class="card-img-top" src="{% static 'assets/img/theme/img-1-1000x600.jpg' %}"/>
       <div class="row justify-content-center">
        <div class="col-lg-3 order-lg-2">
         <div class="card-profile-image">
          <a href="#">
           <img class="rounded-circle" src="{% if user.profile.image %}{{user.profile.image.url}}{% else %}{% static 'assets/img/theme/team-4.jpg' %}{% endif %}"/>
          </a>
         </div>
        </div>
       </div>
       <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
       </div>
       <div class="card-body pt-0">
        <div class="row">
         <div class="col">
          <div class="card-profile-stats d-flex justify-content-center">
           <div>
            <span class="heading">
            </span>
            <span class="description">
            </span>
           </div>
           <div>
            <span class="heading">
             10
            </span>
            <span class="description">
             Likes
            </span>
           </div>
           <div>
            <span class="heading">
            </span>
            <span class="description">
            </span>
           </div>
          </div>
         </div>
        </div>
        <div class="text-center">
         <h5 class="h3">
          {{user.first_name}} {{user.last_name}}
          <span class="font-weight-light">
          </span>
         </h5>
         <div class="h5 font-weight-300">
          <i class="ni location_pin mr-2">
          </i>
        {{user.email}}
         </div>
         <div class="h5 mt-4">
          <i class="ni business_briefcase-24 mr-2">
          </i>
         </div>
         <div>
          <i class="ni education_hat mr-2">
          </i>
         </div>
        </div>
       </div>
      </div>
     </div>
     <div class="col-xl-8 order-xl-1">
      <div class="card">
       <div class="card-header">
        <div class="row align-items-center">
         <div class="col-8">
          <h3 class="mb-0">
           Edit profile
          </h3>
         </div>
        </div>
       </div>
       <div class="card-body">
        <form method="POST" action="{% url 'APP:settings' %}" enctype="multipart/form-data" >
          {% csrf_token %}
         <h6 class="heading-small text-muted mb-4">
          User information
         </h6>
         <div class="pl-lg-4">
          <div class="row">
             <input name="username" type="hidden" value="{{user.username}}"/>
           <div class="col-lg-6">
            <div class="form-group">
             <label class="form-control-label" for="input-email">
              Email address
             </label>
             <input class="form-control" id="input-email" placeholder="jesse@example.com" name="email" type="email" value="{{user.email}}"/>
            </div>
           </div>
          </div>
          <div class="row">
           <div class="col-lg-6">
            <div class="form-group">
             <label class="form-control-label" for="input-first-name">
              First name
             </label>
             <input class="form-control" id="input-first-name" placeholder="First name" name="first_name" type="text" value="{{user.first_name}}"/>
            </div>
           </div>
           <div class="col-lg-6">
            <div class="form-group">
             <label class="form-control-label" for="input-last-name">
              Last name
             </label>
             <input class="form-control" id="input-last-name" placeholder="Last name"  name="last_name" type="text" value="{{user.last_name}}"/>
            </div>
           </div>
           <div class="col-lg-6">
            <div class="form-group">
             <label class="form-control-label" for="input-last-name">
              Picture
             </label>
             <input class="form-control" id="input-last-name" type="file" name="image" value="{{user.profile.image}}"/>
            </div>
           </div>
          </div>
         </div>
         <hr class="my-4">
          <!-- Address -->
          <hr class="my-4"/>
          <!-- Description -->
         </hr>
         <button class="btn btn-primary btn-lg" type="submit">
          Update
        </button>
        </form>
       </div>
      </div>
     </div>
    </div>
    <!-- Footer -->
    <footer class="footer pt-0">
     <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
       <div class="copyright text-center text-lg-left text-muted">
        © 2020
        <a class="font-weight-bold ml-1" href="https://www.creative-tim.com" target="_blank">
         TEAM GREEN
        </a>
       </div>
      </div>
      <div class="col-lg-6">
       <ul class="nav nav-footer justify-content-center justify-content-lg-end">
        <li class="nav-item">
         <a class="nav-link" href="" target="_blank">
          Creative Tim
         </a>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="" target="_blank">
          MIT License
         </a>
        </li>
       </ul>
      </div>
     </div>
    </footer>
   </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}">
  </script>
  <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}">
  </script>
  <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}">
  </script>
  <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}">
  </script>
  <script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}">
  </script>
  <!-- Argon JS -->
  <script src="{% static 'assets/js/argon.js?v=1.2.0' %}">
  </script>
 </body>
</html>